Feature unit tests
TaskarCenterAtUW/TDEI-python-ms-core pull request #21
Opened 2023-07-03 12:42 UTC by sujata-m

- increases test coverage to 81%
- Added unit test cases for 
     - Topic
     - FileEntity
     - Queue
     - Storage Classes
     - Logger Classes
     - Configurations
     - Authorizer
NOTE: The enumeration document is not yet complete. Here are the test results from the above code:
```shell
>  coverage run --source=src/python_ms_core -m unittest discover -v tests/unit_tests
test_has_permission (test_auth.abstract.test_authorizer_abstraction.TestAuthorizerAbstract) ... ok
test_get_search_params (test_auth.models.test_permission_request.TestPermissionRequest) ... ok
test_has_permission_with_invalid_permissions (test_auth.provider.test_hosted_authorizer.TestHostedAuthorizer) ... ok
test_has_permission_with_missing_auth_url (test_auth.provider.test_hosted_authorizer.TestHostedAuthorizer) ... ok
test_has_permission_with_valid_permissions (test_auth.provider.test_hosted_authorizer.TestHostedAuthorizer) ... ok
test_has_permission_should_return_should_satisfy_all (test_auth.provider.test_simulated_authorizer.TestSimulatedAuthorizer) ... ok
test_has_permission_should_return_should_satisfy_none (test_auth.provider.test_simulated_authorizer.TestSimulatedAuthorizer) ... ok
test_core_config_auth (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_auth_url (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_auth_url_default (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_logger (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_provider (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_provider_default (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_provider_override (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_queue (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_queue_connection (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_queue_connection_default (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_queue_name (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_queue_name_default (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_storage (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_storage_connection (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_storage_connection_default (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_topic (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_topic_connection (test_config.test_cofig.TestCoreConfig) ... ok
test_core_config_topic_connection_default (test_config.test_cofig.TestCoreConfig) ... ok
test_local_config_auth (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_logger (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_provider (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_provider_default (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_queue (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_queue_connection (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_queue_connection_default (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_queue_name (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_queue_name_default (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_storage (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_storage_connection (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_storage_connection_default (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_topic (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_topic_connection (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_topic_connection_default (test_config.test_cofig.TestLocalConfig) ... ok
test_local_config_auth (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_logger (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_provider (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_queue (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_queue_connection_default (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_queue_name_default (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_storage (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_storage_connection_default (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_topic (test_config.test_cofig.TestUnknownConfig) ... ok
test_unknown_config_topic_connection_default (test_config.test_cofig.TestUnknownConfig) ... ok
test_get_authorizer_no_config (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: SIMULATED
ok
test_get_authorizer_with_config_hosted_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: AZURE
ok
test_get_authorizer_with_config_simulated_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: SIMULATED
ok
test_get_authorizer_with_config_unknown_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: UNKNOWN
ok
test_get_logger_azure_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: AZURE
ok
test_get_logger_local_provider (test_core.TestCore) ... ok
test_get_logger_unknown_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: UNKNOWN
ok
test_get_storage_client_azure_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: AZURE
ok
test_get_storage_client_local_provider (test_core.TestCore) ... ok
test_get_storage_client_unknown_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: UNKNOWN
ok
test_get_topic_azure_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: AZURE
ok
test_get_topic_local_provider (test_core.TestCore) ... ok
test_get_topic_unknown_provider (test_core.TestCore) ... 2023-07-03 18:07:41 ERROR    Failed to initialization core.get_logger for provider: UNKNOWN
ok
test_add_request (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_debug (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_error (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_info (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_record_metric (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_warn (test_logger.abstract.test_logger_abstract.TestLoggerAbstract) ... ok
test_add_request (test_logger.test_local_logger.TestLocalLogger) ... ok
test_debug (test_logger.test_local_logger.TestLocalLogger) ... ok
test_error (test_logger.test_local_logger.TestLocalLogger) ... ok
test_info (test_logger.test_local_logger.TestLocalLogger) ... ok
test_record_metric (test_logger.test_local_logger.TestLocalLogger) ... ok
test_warn (test_logger.test_local_logger.TestLocalLogger) ... ok
test_add_request (test_logger.test_logger.TestLogger) ... ok
test_debug (test_logger.test_logger.TestLogger) ... ok
test_error (test_logger.test_logger.TestLogger) ... ok
test_info (test_logger.test_logger.TestLogger) ... ok
test_record_metric (test_logger.test_logger.TestLogger) ... ok
test_warn (test_logger.test_logger.TestLogger) ... ok
test_concrete_queue_has_abstract_methods_implemented (test_queue.abstract.test_queue_abstract.TestQueueAbstract) ... ok
test_concrete_queue_inherits_from_queue_abstract (test_queue.abstract.test_queue_abstract.TestQueueAbstract) ... ok
test_azure_provider_invalid_connection_string (test_queue.config.test_queue_config.TestConfig) ... ok
test_a [...]

2023-07-04 05:06 UTC, susrisha approved these changes

2023-07-04 05:06 UTC, susrisha commented on src/python_ms_core/__init__.py
> +                logging.error(f'Failed to initialization core.get_logger for provider: {config}')
Please write as `Failed to initialize core.get_logger `

2023-07-04 05:06 UTC, susrisha commented on src/python_ms_core/__init__.py
> +            logging.error(f'Failed to initialization core.get_topic for provider: {topic_config.provider}')
Please write as `Failed to initialize`

2023-07-04 05:06 UTC, susrisha commented on src/python_ms_core/__init__.py
> +            logging.error(f'Failed to initialization core.get_storage_client for provider: {storage_config.provider}')
`Failed to initialize`

2023-07-04 05:06 UTC, susrisha commented on src/python_ms_core/__init__.py
> +            logging.error(f'Failed to initialization core.get_storage_client for provider: {storage_config.provider}')
`Failed to initialize`

2023-07-04 05:06 UTC, susrisha commented on src/python_ms_core/__init__.py
> +            logging.error(f'Failed to initialization core.get_authorizer for provider: {auth_config.provider}')
`Failed to initialize

2023-07-06 15:28 UTC, sureshgaussian requested changes
I think unittest was not added to the requirements. Following readme.md is failing on my system.

(TDEI) suresh@pavan:~/code/TDEI/TDEI-python-ms-core$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: azure-common==1.1.28 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.1.28)
Requirement already satisfied: azure-core==1.26.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.26.1)
Requirement already satisfied: azure-servicebus==7.0.0 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (7.0.0)
Requirement already satisfied: azure-storage-blob==12.14.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (12.14.1)
Requirement already satisfied: certifi==2022.12.7 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2022.12.7)
Requirement already satisfied: cffi==1.15.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: charset-normalizer==2.1.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (2.1.1)
Requirement already satisfied: cryptography==39.0.0 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (39.0.0)
Requirement already satisfied: idna==3.4 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (3.4)
Requirement already satisfied: isodate==0.6.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (0.6.1)
Requirement already satisfied: msrest==0.7.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.7.1)
Requirement already satisfied: oauthlib==3.2.2 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (3.2.2)
Requirement already satisfied: pycparser==2.21 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 13)) (2.21)
Requirement already satisfied: python-dotenv==0.21.0 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (0.21.0)
Requirement already satisfied: requests==2.28.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (2.28.1)
Requirement already satisfied: requests-oauthlib==1.3.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (1.3.1)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: typing_extensions==4.4.0 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (4.4.0)
Requirement already satisfied: uamqp==1.6.3 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (1.6.3)
Requirement already satisfied: urllib3==1.26.14 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (1.26.14)
Requirement already satisfied: pika==1.3.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (1.3.1)
Requirement already satisfied: httpx==0.24.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (0.24.1)
Requirement already satisfied: coverage==7.2.7 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 23)) (7.2.7)
Requirement already satisfied: html_testRunner==1.2.1 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 24)) (1.2.1)
Requirement already satisfied: psutil==5.9.5 in /home/suresh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 25)) (5.9.5)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /home/suresh/.local/lib/python3.10/site-packages (from httpx==0.24.1->-r requirements.txt (line 22)) (0.17.2)
Requirement already satisfied: sniffio in /home/suresh/.local/lib/python3.10/site-packages (from httpx==0.24.1->-r requirements.txt (line 22)) (1.3.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/lib/python3/dist-packages (from html_testRunner==1.2.1->-r requirements.txt (line 24)) (3.0.3)
Requirement already satisfied: h11<0.15,>=0.13 in /home/suresh/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->-r requirements.txt (line 22)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /home/suresh/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->-r requirements.txt (line 22)) (3.6.2)
(TDEI) suresh@pavan:~/code/TDEI/TDEI-python-ms-core$ unittest discover -v tests/unit_tests
unittest: command not found
(TDEI) suresh@pavan:~/code/TDEI/TDEI-python-ms-core$ cd tests/
(TDEI) suresh@pavan:~/code/TDEI/TDEI-python-ms-core/tests$ unittest discover -v tests/unit_tests
unittest: command not found

2023-09-07 10:26 UTC, sureshgaussian approved these changes

2023-09-07 10:27 UTC, merged